// JsFromRoutes CacheKey 86e4c12f22daf43446808268ba205c0e
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  new: /* #__PURE__ */ definePathHelper('get', '/users/sign_in'),
  create: /* #__PURE__ */ definePathHelper('post', '/users/sign_in'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/users/sign_out'),
  guestSignIn: /* #__PURE__ */ definePathHelper('get', '/guest_sign_in'),
}
