// JsFromRoutes CacheKey af3b3cd4a1d26c28c8eda958c64e3958
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/bots'),
  new: /* #__PURE__ */ definePathHelper('get', '/bots/new'),
}
