// JsFromRoutes CacheKey 45e1530699628dd0b81f5190fdc3852e
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  show: /* #__PURE__ */ definePathHelper('get', '/chats/:username'),
  index: /* #__PURE__ */ definePathHelper('get', '/chats'),
  create: /* #__PURE__ */ definePathHelper('post', '/chats'),
  new: /* #__PURE__ */ definePathHelper('get', '/chats/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/chats/:id/edit'),
  update: /* #__PURE__ */ definePathHelper('patch', '/chats/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/chats/:id'),
}
