// JsFromRoutes CacheKey 3dda43801a422612474d30b32bb4e301
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/posts/:post_id/comments/:comment_id/replies'),
  post: /* #__PURE__ */ definePathHelper('get', '/posts/:post_id/comments'),
  create: /* #__PURE__ */ definePathHelper('post', '/posts/:post_id/comments/:comment_id/replies'),
  createPost: /* #__PURE__ */ definePathHelper('post', '/posts/:post_id/comments'),
  new: /* #__PURE__ */ definePathHelper('get', '/posts/:post_id/comments/:comment_id/replies/new'),
  newPostComment: /* #__PURE__ */ definePathHelper('get', '/posts/:post_id/comments/new'),
}
