// JsFromRoutes CacheKey 3b4073bfd7c9180b73f71e6fde47c4b0
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/profiles/:profile_username/follows'),
  accept: /* #__PURE__ */ definePathHelper('patch', '/follows/:id/accept'),
  create: /* #__PURE__ */ definePathHelper('post', '/follows'),
  new: /* #__PURE__ */ definePathHelper('get', '/follows/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/follows/:id/edit'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/follows/:id'),
}
