// JsFromRoutes CacheKey 02e99ceb7c4c7e903e68cfc1b31e25a1
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  like: /* #__PURE__ */ definePathHelper('post', '/posts/:id/like'),
  unlike: /* #__PURE__ */ definePathHelper('delete', '/posts/:id/like'),
  index: /* #__PURE__ */ definePathHelper('get', '/posts'),
  root: /* #__PURE__ */ definePathHelper('get', '/'),
  create: /* #__PURE__ */ definePathHelper('post', '/posts'),
  new: /* #__PURE__ */ definePathHelper('get', '/posts/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/posts/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/posts/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/posts/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/posts/:id'),
}
