// JsFromRoutes CacheKey 6796ea94955bc14ac92682175aaaf081
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  followStatus: /* #__PURE__ */ definePathHelper('get', '/profiles/:username/follow_status'),
  search: /* #__PURE__ */ definePathHelper('get', '/profiles/search'),
  index: /* #__PURE__ */ definePathHelper('get', '/profiles'),
  create: /* #__PURE__ */ definePathHelper('post', '/profiles'),
  new: /* #__PURE__ */ definePathHelper('get', '/profiles/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/profiles/:username/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/profiles/:username'),
  update: /* #__PURE__ */ definePathHelper('patch', '/profiles/:username'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/profiles/:username'),
}
