// JsFromRoutes CacheKey 8cd5106a47121d97aa944f766fab547d
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/webauthn/auth'),
  create: /* #__PURE__ */ definePathHelper('post', '/webauthn/auth'),
}
