// JsFromRoutes CacheKey 8e781532c6b317279ec04616ea28b2d8
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/webauthn/credentials'),
  create: /* #__PURE__ */ definePathHelper('post', '/webauthn/credentials'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/webauthn/credentials/:id'),
}
