// JsFromRoutes CacheKey 93d16d7a3ac28194c6f66ee5a95fa7d3
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/webauthn/credentials/challenge'),
}
