// JsFromRoutes CacheKey 60e004f596e09c0ae2f14248e05a3501
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/webauthn/auth/challenge'),
}
